language: java
jdk: "-openjdk11"
env:
  global:
  - CODECOV_TOKEN='9b3f4403-014a-4ea3-b09a-bc93708a17b8'
  - env='DEV'
  - secure: w5DXm9a/1BlRre1KwQ/77ZoiBkb6IVz64DFFj03l7ryEwoX2+3HHp8d9l6KZCIBstK5Ftqn71OKfgLeJEgpA0T3SLqd1kILAILMPS6BBlatz0gvWBUZKY1N4IxZZdabIlDaIFtq8iuT689SYL76Mk0zn6QzcW7G+M1+6IzKWMJaW6+4O0A9HuHklWOaZA/E1Mk0Cf4oeFg07gU6oe7bD5jxVJBpC96gsVyMHhdR/HFmOZIyQMUP5Ls74BDq9S6i2A3g2SN1GhWGrGRyZKHEkJ6GvfS29AZS23Hs1ebrE3JflohYNPORGuVWQmvSS2UPFQUuP+FsDSX5gKFIz8qoYlGXJgJgcNiTeVRnyq0HA6eXSczEBMWgkD1Bi9NGWgmqLn76b0EeLDLJHupUDEkD820IaBW+QACJeTjEGY0ZRsZXtSdJQp6LnC6pm1e34wSSlKvu3Rt+MxjXam1mTmB3N2TfH5WOQkKvMdrgnkcigj+LtcADnmeki4VtZ3WVZ20wc3Kn2LvVV2t1Ci+jsvl+dEkt+JPgwwHrld5XBx5f73BX1B/NXGx5fBjOCK2jF3d3pfFvLRbm/5q6rrQvL7cly+sZNSMrq2HUln0CyZqvasVf82vfzVBR7V9oq9h+LjMoeZxT938vtvfBKnuJ5DxFP3Yf1FJzihKl2nF5ez3POvQE=
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: w5DXm9a/1BlRre1KwQ/77ZoiBkb6IVz64DFFj03l7ryEwoX2+3HHp8d9l6KZCIBstK5Ftqn71OKfgLeJEgpA0T3SLqd1kILAILMPS6BBlatz0gvWBUZKY1N4IxZZdabIlDaIFtq8iuT689SYL76Mk0zn6QzcW7G+M1+6IzKWMJaW6+4O0A9HuHklWOaZA/E1Mk0Cf4oeFg07gU6oe7bD5jxVJBpC96gsVyMHhdR/HFmOZIyQMUP5Ls74BDq9S6i2A3g2SN1GhWGrGRyZKHEkJ6GvfS29AZS23Hs1ebrE3JflohYNPORGuVWQmvSS2UPFQUuP+FsDSX5gKFIz8qoYlGXJgJgcNiTeVRnyq0HA6eXSczEBMWgkD1Bi9NGWgmqLn76b0EeLDLJHupUDEkD820IaBW+QACJeTjEGY0ZRsZXtSdJQp6LnC6pm1e34wSSlKvu3Rt+MxjXam1mTmB3N2TfH5WOQkKvMdrgnkcigj+LtcADnmeki4VtZ3WVZ20wc3Kn2LvVV2t1Ci+jsvl+dEkt+JPgwwHrld5XBx5f73BX1B/NXGx5fBjOCK2jF3d3pfFvLRbm/5q6rrQvL7cly+sZNSMrq2HUln0CyZqvasVf82vfzVBR7V9oq9h+LjMoeZxT938vtvfBKnuJ5DxFP3Yf1FJzihKl2nF5ez3POvQE=
  email: glushkov18@gmail.com
services:
- postgresql
deploy:
  provider: heroku
  app: wax-deals
  on:
    branch: develop
  strategy: git
  api_key:
    secure: u68eGuIPSuV9OIVw2/wpWvq7MZUnxcx6SViz2iGu4Ss0b2yMYLRF8Ev6fGHhoiKOkBqnW503+CbA6dmOVBoKr5ETJCMqVdqamV0CJ2C2k3jq8v3UywhAq+7l7Z4IxRHfmm8nLFc5xUOQ6B6Fy3zZgJZN7MsjPr4UrfJ86qVdHbrhROWw/R5T8mLJf6pmvrYTiaqvGXiasYXo12zCv6+LCn9lmA4SDKR4pJZDWe5ifWQa3DQ19xQMnDN578d5uQiuS2jxKyWw9Iy9Qx4FRUR2DLOXDdNd8epqBMDcxPMsO9kCuL4F0Yjc+KZFIDB6bO0zp+xUyY86zKZGxvQe6SUdApORW9p8sFJA80Jx+8+4wpJSvc+bsyq/8DeYLwaJiNqVHs9MIB9m519Ko8dzU/w2UxPVlrKKro+CFxOQHEvZXpkRV/LtiNHFPvQ4IrIepnOpy9J10QdKqe/GqCIAKkniGxtRnZ4EtPAym8LVYu/bIf5MQfqNEbodvdmSfnCtmr9QXNent26xoN5v+LXOpjYmTlY8ea6d5QjnGrnn2WIupBq/QtErQN6vmGG5EJQs8E1PxPmIzAcrSm1SOnRod33OCYD2PSMjM2fsXB6xHf2/6er4/Qa3pfyyDJNQ80WQicJ4XuMYyqnqhFpqasBKrA6Qxgy+DengCIO+4f7IRm0/7Aw=
