language: java
jdk: "-openjdk11"
install: travis_wait 60 mvn install
env:
  global:
    - CODECOV_TOKEN='9b3f4403-014a-4ea3-b09a-bc93708a17b8'
    - env='DEV'
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: VZDMLZ2zEmzIUW0wUaiNsjpsgLmCeKSzDOodo8tiRXHGOjt79dYQi5zMWEMKaSzphCEUgsOaEXdWnUcvsmP5WosNdWXQ51LOdKaBVcJJUVT3bB9l3awc+mqw9s3iUplEV//D1NwFg19hJL2PUAdP4hP8HNoZAk+C3fbuNHtVsJXZW3xpiczvRArAfKcS9ErxefiZWqGs40idZyC9D0WLW8uEpPD2DGFn/O8RJLpCe5sD/t7TwtydSineAvNMsLt1YsdBadht4DWGn/YF4GEWKNvGCF34hSQwb1oynrZV0MpxiCrdlKtPKms8RoWMSuwusrKR7LT0tdY2p0REpcouecjFJFuHB1XNcC3lRXsAtWLjCd3Uye4r6RHAepMn4xwG7JVyH6n5ZPCnnsISpQEST+4AIbzdxrdtWK0eahJxU8nqyapxAHBzBObBeXOlnwj25tEwny3HvTGgQ92uTPZBUp5lz4cWgIKroURhle7BeO/6r5a1nKOzva+fyfzUG04zeIsoFb3fd63sj6oazEGywX45hKqDy+V6XY5jUnxC2W8NFEKtYVVcD73AKPo+rBvO8arEzV6Oqe68HaS4i/A9KZJoiKFFxZN2aEl5En5YJNvBVpT7H7rZ3WHfCZOF9dquYLuIYojap0UfbwrjMjXI9tk6H5r+EVpqtUQtpf7QwKg=
  email: glushkov18@gmail.com
services:
  - postgresql
deploy:
  provider: heroku
  app: wax-deals
  on:
    branch: develop
  strategy: git
  api_key:
    secure: u68eGuIPSuV9OIVw2/wpWvq7MZUnxcx6SViz2iGu4Ss0b2yMYLRF8Ev6fGHhoiKOkBqnW503+CbA6dmOVBoKr5ETJCMqVdqamV0CJ2C2k3jq8v3UywhAq+7l7Z4IxRHfmm8nLFc5xUOQ6B6Fy3zZgJZN7MsjPr4UrfJ86qVdHbrhROWw/R5T8mLJf6pmvrYTiaqvGXiasYXo12zCv6+LCn9lmA4SDKR4pJZDWe5ifWQa3DQ19xQMnDN578d5uQiuS2jxKyWw9Iy9Qx4FRUR2DLOXDdNd8epqBMDcxPMsO9kCuL4F0Yjc+KZFIDB6bO0zp+xUyY86zKZGxvQe6SUdApORW9p8sFJA80Jx+8+4wpJSvc+bsyq/8DeYLwaJiNqVHs9MIB9m519Ko8dzU/w2UxPVlrKKro+CFxOQHEvZXpkRV/LtiNHFPvQ4IrIepnOpy9J10QdKqe/GqCIAKkniGxtRnZ4EtPAym8LVYu/bIf5MQfqNEbodvdmSfnCtmr9QXNent26xoN5v+LXOpjYmTlY8ea6d5QjnGrnn2WIupBq/QtErQN6vmGG5EJQs8E1PxPmIzAcrSm1SOnRod33OCYD2PSMjM2fsXB6xHf2/6er4/Qa3pfyyDJNQ80WQicJ4XuMYyqnqhFpqasBKrA6Qxgy+DengCIO+4f7IRm0/7Aw=




