codecov:
  token: "9b3f4403-014a-4ea3-b09a-bc93708a17b8"
  require_ci_to_pass: yes

coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
        only_pulls: true
        branches:
          - "develop"
        flags:
          - "unit"
        paths:
          - "src"
  precision: 2
  round: down
  range: "70...100"



ignore:
  - "src/main/java/com/vinylteam/vinyl/discogs4j"
  - "src/main/java/com/vinylteam/vinyl/entity"



